# Generated by Django 2.0 on 2021-08-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='role', max_length=255)),
                ('fotp', models.IntegerField(default=123456)),
                ('email', models.EmailField(default='email', max_length=254, unique=True)),
                ('password', models.CharField(default='password', max_length=255)),
                ('address', models.CharField(default='addres', max_length=255)),
                ('Is_created', models.DateField(auto_now_add=True)),
                ('Is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('reason', models.CharField(default='reason', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='firsname', max_length=255)),
                ('lname', models.CharField(default='lastname', max_length=255)),
                ('address', models.CharField(default='addres', max_length=255)),
                ('bdate', models.DateField(null=True)),
                ('phone', models.BigIntegerField(default=123456)),
                ('gender', models.CharField(default='gender', max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_app.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='expense_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('Prove', models.FileField(default='.jpg', upload_to='img/')),
                ('Payment', models.IntegerField(default=22)),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='firsname', max_length=255)),
                ('lname', models.CharField(default='lastname', max_length=255)),
                ('address', models.CharField(default='addres', max_length=255)),
                ('bdate', models.DateField(null=True)),
                ('phone', models.BigIntegerField(default=1234567890)),
                ('gender', models.CharField(default='gender', max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_app.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='leave_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('reason', models.CharField(default='reason', max_length=255)),
                ('hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_app.Hr')),
            ],
        ),
        migrations.CreateModel(
            name='shifte_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('reason', models.CharField(default='reason', max_length=255)),
                ('hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_app.Hr')),
            ],
        ),
        migrations.AddField(
            model_name='expense_req',
            name='hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_app.Hr'),
        ),
        migrations.AddField(
            model_name='attendance_request',
            name='hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_app.Hr'),
        ),
    ]
