# Generated by Django 2.0 on 2021-08-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_shift_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('reason', models.CharField(default='reason', max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_app.emp')),
            ],
        ),
    ]
