# Generated by Django 2.0 on 2021-08-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_app', '0002_emp_shift_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_leave_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('reason', models.CharField(default='reason', max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_app.emp')),
            ],
        ),
        migrations.AddField(
            model_name='attendance_request',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='emp_shift_req',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='expense_req',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='leave_request',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='shifte_request',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
