# Generated by Django 2.0 on 2021-08-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_app', '0003_auto_20210813_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_attendance_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('reason', models.CharField(default='reason', max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_app.emp')),
            ],
        ),
    ]
