# Generated by Django 2.0 on 2021-08-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_app', '0004_emp_attendance_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_expense_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('Prove', models.FileField(default='.jpg', upload_to='img/')),
                ('Payment', models.IntegerField(default=22)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_app.emp')),
            ],
        ),
    ]
