# Generated by Django 2.0 on 2021-08-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_app', '0006_emp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='active',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
